erDiagram
    organization ||--|{ organization_module : has
    organization {
      id int 
      name text 
      password text 
      email text 
      daily_or_weekly notification_frequency 
    }
    
    organization_module ||--|| module : has
    organization_module {
      module_id int
      organization_id int
    }

    module ||--|{ module_version : has
    module {
      id int 
      name text 
    }

    module_version {
      id int 
      text  name
      published timestamp
      module_id int
    }

    organization ||--|{ job : has
    job {
      id int
      name text
      description text
      organization_id int
      starts_at timestamp
      schedule daily_or_weekly
    }